name: firebase_service
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:

  # Shared
  core_dependencies:
    path: ../../dependencies/core_dependencies
  firebase_dependencies:
    path: ../../dependencies/firebase_dependencies