name: notification_repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

  # Shared
  firebase_dependencies:
    path: ../../dependencies/firebase_dependencies
  shared_dependencies:
    path: ../../dependencies/shared_dependencies

dev_dependencies:
  build_runner:
  json_serializable: ^6.7.0