name: bloc_app
description: App with bloc.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  hydrated_bloc: ^9.1.1
  json_annotation: ^4.8.1

  # Services
  firebase_service:
    path: ../../services/firebase_service

  # Repositories
  authentication_repository:
    path: ../../repositories/authentication_repository
  firestore_user_repository:
    path: ../../repositories/firestore_user_repository
  notification_repository:
    path: ../../repositories/notification_repository

  # Shared
  firebase_dependencies:
    path: ../../dependencies/firebase_dependencies
  firebase_ui_dependencies:
    path: ../../dependencies/firebase_ui_dependencies
  shared_dependencies:
    path: ../../dependencies/shared_dependencies
  styleguide:
    path: ../../styleguide
  shared_assets:
    path: ../../dependencies/shared_assets

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf