name: provider_app
description: App with Provider.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State
  provider: ^6.0.5

  # Services
  firebase_service:
    path: ../../services/firebase_service

  # Repositories
  authentication_repository:
    path: ../../repositories/authentication_repository

  # Shared
  firebase_dependencies:
    path: ../../dependencies/firebase_dependencies
  shared_dependencies:
    path: ../../dependencies/shared_dependencies
  styleguide:
    path: ../../styleguide

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf