name: utils
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.1
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  very_good_analysis: ^4.0.0+1
