name: shared_dependencies
description: Used in all apps.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  app_settings: ^4.2.0
  dartz: ^0.10.1
  flex_color_scheme: ^7.1.2
  flutter_local_notifications: ^14.1.1
  google_fonts: ^4.0.4
  grouped_list: ^5.1.2
  intl: ^0.18.0
  mocktail: ^0.3.0
  nb_utils: ^5.0.8
  package_info_plus: ^4.0.1
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  url_launcher: ^6.1.11
  very_good_analysis: ^4.0.0+1
  vrouter: ^1.2.1
