name: shared_dependencies
description: Used in all apps.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  app_settings: ^4.2.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  dio: ^5.2.1+1
  flex_color_scheme: ^7.1.2
  flutter_local_notifications: ^14.1.1
  flutter_staggered_grid_view: ^0.6.2
  geocoding: ^2.1.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.3.1
  grouped_list: ^5.1.2
  image_picker: ^1.0.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.0
  mocktail: ^0.3.0
  modal_bottom_sheet: ^3.0.0-pre
  nb_utils: ^6.0.0
  package_info_plus: ^4.0.1
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  rxdart: ^0.27.7
  url_launcher: ^6.1.11
  vrouter: ^1.2.1
  welltested_annotation: ^1.0.1
