name: location_service
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Shared
  core_dependencies:
    path: ../../dependencies/core_dependencies