name: riverpod_app
description: App with Riverpod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3

  # Services
  authentication_service:
    path: ../../services/authentication_service
  firebase_service:
    path: ../../services/firebase_service

  # Repositories

  # Shared
  firebase_dependencies:
    path: ../../dependencies/firebase_dependencies
  shared_dependencies:
    path: ../../dependencies/shared_dependencies
  styleguide:
    path: ../../styleguide

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf