name: riverpod_app
description: App with Riverpod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.0

  # Services
  authentication_service:
    path: ../../services/authentication_service
  firebase_service:
    path: ../../services/firebase_service
  location_service:
    path: ../../services/location_service
  notification_service:
    path: ../../services/notification_service

  # Repositories
  api_repository:
    path: ../../repositories/api_repository
  firestore_image_repository:
    path: ../../repositories/firestore_image_repository
  firestore_user_repository:
    path: ../../repositories/firestore_user_repository
  realtime_chat_repository:
    path: ../../repositories/realtime_chat_repository

  # Shared
  core_dependencies:
    path: ../../dependencies/core_dependencies
  firebase_dependencies:
    path: ../../dependencies/firebase_dependencies
  shared_dependencies:
    path: ../../dependencies/shared_dependencies
  styleguide:
    path: ../../styleguide
  shared_assets:
    path: ../../dependencies/shared_assets
  utils:
    path: ../../utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  custom_lint:
  riverpod_lint:

flutter:
  uses-material-design: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf