name: authentication_service
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  # Shared
  core_dependencies:
    path: ../../dependencies/core_dependencies
  firebase_dependencies:
    path: ../../dependencies/firebase_dependencies